export const projects = [
  {
    title: 'Social Network',
    description: "Социальная сеть. В качестве backend использован внешний сервер. Добавлен TypeScript. Вкладка Chat организована с помощью WebSocket. Упор сделан на функционал. Login: free@samuraijs.com  Password: free",
      image: '/images/Sn1.png',
      tags: ['TypeScript', "JS", 'React', 'REDUX', 'WebSocket'],
    source: 'https://github.com/Viktorovich-buil/SocialNetWork',
    visit: 'https://viktorovich-buil.github.io/32/',
    id: 0,
  },
  {
    title: 'TOPLINK',
    description:"Интернет магазин. В качестве backend использован Commerce.js. Подключен Stripe для выполнения транзакций. Для стилизации использованы компоненты Material-UI",
    image: '/images/Webshop1.png',
    tags: ['JS', 'React', 'Commerce'],
    source: 'https://github.com/Viktorovich-buil/TOPLINK',
    visit: 'https://toplink-commercejs.netlify.app/',
    id: 1,
  },
  {
    title: 'MyMap',
    description: "Используя Full Stack 'MERN' создано приложение позволяющее создать аккаунт и оставить свою метку на карте мира с описанием. В качестве сервера использован MapBox",
      image: '/images/Mymap1.png',
      tags: ['JS', 'MongoDB', 'Express', 'React', 'Node'],
    source: 'https://github.com/Viktorovich-buil/MyMap',
    visit: 'https://mernmymap.netlify.app/',
    id: 2,
  },
  {
    title: 'CryptoList',
    description: "Простое приложение которое отслеживает стоимость криптовалют по запросам на API. Возможность поиска.",
    image: '/images/Crypto1.png',
    tags: ['JS', 'React', 'Next'],
    source: 'https://github.com/Viktorovich-buil/Crypto_List',
    visit: 'http://crypto-list.vercel.app/',
    id: 3,
  },
  {
    title: 'Nautic',
    description: "Одностраничный интернет-магазин с адаптивной версткой. Подгрузка товаров из JSON. Добавление и удаление товаров из корзины.",
    image: '/images/Nautic.png',
    tags: ['JS', 'GULP', 'SCSS'],
    source: 'https://github.com/Viktorovich-buil/nautica',
    visit: 'https://nautic.netlify.app/',
    id: 4,
  },
];

// {
//   title: 'MERN Memories',
//       description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
//     image: '/images/1.png',
//     tags: ['Mongo', 'Express', 'React', 'Node'],
//     source: 'https://google.com',
//     visit: 'https://google.com',
//     id: 0,
// },
// {
//   title: 'E-Commerce',
//       description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
//     image: '/images/2.png',
//     tags: ['React', 'JavaScript'],
//     source: 'https://google.com',
//     visit: 'https://google.com',
//     id: 1,
// },
// {
//   title: 'WebRTC App',
//       description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
//     image: '/images/3.jpg',
//     tags: ['React', 'WebRTC'],
//     source: 'https://google.com',
//     visit: 'https://google.com',
//     id: 2,
// },
// {
//   title: 'Unichat',
//       description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
//     image: '/images/4.jpg',
//     tags: ['React', 'ChatEngine', 'Firebase'],
//     source: 'https://google.com',
//     visit: 'https://google.com',
//     id: 3,
// },



export const TimeLineData = [
  { year: 2017, text: 'Начальник технического отдела на строительстве крупных объктов', },
  { year: 2018, text: 'Работа на объектах РОСАТОМ. Внедрение производственной системы с использованием Primavera', },
  { year: 2019, text: 'Заместитель генерального директора в частной организации', },
  { year: 2020, text: 'Начало изучения web-разработки', },
  { year: 2021, text: 'Работа фрилансером', },
];
